# Generated by Django 3.2.5 on 2021-12-30 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofielinfo',
            old_name='porfolio_site',
            new_name='portfolio_site',
        ),
    ]
